### ISSUE TITLE
Supporting shrinkwrap ?

### ISSUE THREAD

**Issue by Offirmo** [plaid/npmserve#18]
serious production code uses npm shrinkwrap. The pair package.json + shrinkwrap is the hash. Do you handle it or just package.json ?

P.S. https://github.com/vvo/npm-pkgr does it correctly, but is local only unlike your nice tool !

**Comment by rbuckheit** [comment]
Hi @Offirmo, `npmserve` is still a development tool (not production ready). It does not support shrinkwrap. We have an open issue to investigate this issue more thoroughly here in the server project:

https://github.com/plaid/npmserve-server/issues/11

Going to close this one out as a dupe, but please do feel free to add comments over in that ticket!
